version: '2'
services:
    locations_cas_react-app:
        image: locations_cas_react
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=locations_cas_react-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    locations_cas_react-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: locations_cas_react-cassandra
    locations_cas_react-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=locations_cas_react-cassandra
    locations_cas_react-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: locations_cas_react-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
