version: '2'
services:
    locations_cas_react-cassandra:
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/locations_cas_react/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    locations_cas_react-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=locations_cas_react-cassandra
    locations_cas_react-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: locations_cas_react-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
